### ISSUE TITLE
"Jest encountered an unexpected token" while importing from angular core

### ISSUE THREAD

**Issue by distante** [datencia/ionic2-jest-example#19]
I am switching from Karma to Jest and I am facing this problem while running some tests and I am not sure what I have to do to fix it.

> Jest encountered an unexpected token

```
Details:

    C:\distante\node_modules\ionic-angular\platform\platform.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { EventEmitter } from '@angular/core';
                                                                                                    ^

    SyntaxError: Unexpected token {

      4 | import { Device } from '@ionic-native/device';
    > 5 | import { Platform } from 'ionic-angular/platform/platform';
        | ^
      6 | import { AppGlobalConstants } from '../models/app-global-constants';
      7 |
      8 | export enum StorageStatus {

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/providers/ssd-secure-storage.service.ts:5:1)
```

tsconfig.spec.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "target": "es5",
    "allowJs": true
  },
  "include": [
    "**/*.spec.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

package.json config

```
 "jest": {
        "preset": "jest-preset-angular",
        "roots": [
            "src"
        ],
        "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts",
        "transformIgnorePatterns": [
            "node_modules/(?!@ngrx|@ionic-native|@ionic)"
        ]
    },
```

And In case need my test:
```
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { TranslateModule } from '@ngx-translate/core';
import { IonicModule } from 'ionic-angular';

import { TrainingTypes } from '../../enums/training-types.enum';
import { HelpersProvider } from '../../providers/helpers/helpers.service';
import { HomePage } from './home';

function randomIndex(max: number) {
    max = Math.floor(max);
    let min = 0;
    let randomIndex = Math.floor(Math.random() * (max - min + 1)) + min;
    return randomIndex;
}

describe("HomePage", () => {
    let component: HomePage;
    let fixture: ComponentFixture<HomePage>;
    const trainingTypesArray: TrainingTypes[] = HelpersProvider.getArrayWithNumberBaseEnumItems(TrainingTypes);

    beforeEach(() => {
        trainingTypesArray.forEach(training => {
           
        });
       
        TestBed.configureTestingModule({
            declarations: [HomePage],
            schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
            
            imports: [IonicModule.forRoot(HomePage),
            TranslateModule.forRoot()]
        });
        fixture = TestBed.createComponent(HomePage);
        component = fixture.componentInstance;
    });

   
});

```

Ionic Info:

```
Ionic:

   ionic (Ionic CLI)  : 4.5.0 (C:\Users\distante\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 22 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\distante\AppData\Local\Android\sdk)
   NodeJS            : v10.14.1 (C:\Program Files\nodejs\node.exe)
   npm               : 6.5.0
   OS                : Windows 10
```

**Comment by datencia** [comment]
Hi, sorry for the delay.

why are you importing the `Platform` as
`import { Platform } from 'ionic-angular/platform/platform';`
?

Instead of that try this:
`import { Platform } from 'ionic-angular';`

**Comment by distante** [comment]
Hello!, no problem for the delay.

> why are you importing the `Platform` as
> `import { Platform } from 'ionic-angular/platform/platform';`
> ?

No idea... probably my IDE did that I did not notice.

> 
> Instead of that try this:
> `import { Platform } from 'ionic-angular';`

Looks like it worked. I would never catch that up because it worked on Karma and I thought it was a problem with jest.

**Comment by datencia** [comment]
ok, anyway I'll try to investigate it.
